# Generated by Django 3.2.7 on 2022-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbank_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='h_id',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='h_id',
        ),
        migrations.RemoveField(
            model_name='request_blood',
            name='h_id',
        ),
        migrations.AddField(
            model_name='donor',
            name='d_otp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='d_otp_used',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='b_contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='dob',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Hospitals',
        ),
    ]
