# Generated by Django 3.2.7 on 2022-01-30 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbank_admin', '0002_auto_20220129_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receiver',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='receiver_id',
            new_name='u_id',
        ),
        migrations.RenameField(
            model_name='request_blood',
            old_name='receiver_id',
            new_name='u_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='receiver_id',
            new_name='u_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='receiver_weight',
            new_name='user_weight',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='d_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='u_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='bbank_admin.user'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='bloodbank_user',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
