# Generated by Django 3.2.7 on 2022-01-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbank_admin', '0005_alter_user_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_gender',
            field=models.CharField(max_length=7),
        ),
    ]
