# Generated by Django 3.2.7 on 2022-02-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbank_admin', '0006_alter_admin_admin_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='b_img',
            field=models.FileField(default=-1, upload_to=''),
            preserve_default=False,
        ),
    ]
