# Generated by Django 3.2.7 on 2022-02-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbank_admin', '0007_bloodbank_b_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='donation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='Description',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Ratings',
            field=models.IntegerField(default=5, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='given_date',
            field=models.DateField(),
        ),
    ]
