# Generated by Django 3.2.7 on 2022-02-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbank_admin', '0008_auto_20220227_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='Description',
        ),
    ]
