# Generated by Django 3.2.7 on 2022-02-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbank_admin', '0009_remove_bloodbank_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='donation_date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Ratings',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(),
        ),
    ]
